### ISSUE TITLE
建议添加魔方转体功能

### ISSUE THREAD

**Issue by ElainaFanBoy** [initialencounter/cube#3]
有时候做起来有点难受（）

**Comment by initialencounter** [comment]
谢谢你!  Thank you!

**Comment by ElainaFanBoy** [comment]
> 谢谢你!  Thank you!

我去，秒回复，爱了爱了
插件还是很好玩的说，作者辛苦了
![-7c402c68c0841d92.jpg](https://user-images.githubusercontent.com/56375835/235677312-8977f3cd-34bc-4243-8f00-6ac23a2befe5.jpg)
